# -*- coding: utf-8 -*-
"""
配置模块
"""

from .default_config import (
    # 图像处理
    IMAGENET_MEAN, IMAGENET_STD,
    SUPPORTED_IMAGE_FORMATS,
    IMAGE_SIZE_OPTIONS, DEFAULT_IMAGE_SIZE,
    
    # Backbone
    BACKBONE_OPTIONS, DEFAULT_BACKBONE, DEFAULT_LAYERS,
    
    # Memory Bank
    DEFAULT_CORESET_RATIO, MIN_CORESET_RATIO, MAX_CORESET_RATIO,
    DEFAULT_PCA_COMPONENTS, PCA_VARIANCE_THRESHOLD, AUTO_PCA_THRESHOLD_DIM,
    DEFAULT_KNN_K, MIN_KNN_K, MAX_KNN_K,
    
    # 阈值
    SCORE_RANGE, DEFAULT_THRESHOLD, THRESHOLD_PRESETS,
    CALIBRATION_PERCENTILES,
    
    # 导出
    EXPORT_FORMATS, DEFAULT_EXPORT_FORMAT,
    TENSORRT_PRECISIONS, DEFAULT_TENSORRT_PRECISION,
    FAISS_INDEX_TYPES, FAISS_AUTO_THRESHOLDS,
    
    # 优化
    DEFAULT_USE_FP16_FEATURES, DEFAULT_FEATURE_CHUNK_SIZE,
    DEFAULT_INCREMENTAL_PCA, DEFAULT_PCA_BATCH_SIZE,
    DEFAULT_RANDOM_PROJECTION_DIM, DEFAULT_CORESET_MAX_ITER,
    DEFAULT_FEATURE_BATCH_SIZE, DEFAULT_INFERENCE_BATCH_SIZE,
    
    # 输出
    OUTPUT_DIRS, OUTPUT_FILENAMES,
    
    # 设备
    DEVICE_OPTIONS, DEFAULT_DEVICE,
    
    # 后处理
    DEFAULT_GAUSSIAN_SIGMA, DEFAULT_GAUSSIAN_KERNEL_SIZE,
    DEFAULT_UPSAMPLE_MODE,
    
    # 可视化
    HEATMAP_COLORMAP, CONTOUR_COLOR, CONTOUR_THICKNESS,
    
    # 场景模板
    SCENE_TEMPLATES, AUGMENTATION_CONFIG,
)

from .training_config import (
    TrainingConfig,
    BackboneConfig,
    MemoryBankConfig,
    KNNConfig,
    PostprocessConfig,
    NormalizationConfig,
    ThresholdConfig,
    ExportConfig,
    OptimizationConfig,
    AugmentationConfig,
    get_backbone_info,
)

__all__ = [
    # 常量
    'IMAGENET_MEAN', 'IMAGENET_STD',
    'SUPPORTED_IMAGE_FORMATS',
    'IMAGE_SIZE_OPTIONS', 'DEFAULT_IMAGE_SIZE',
    'BACKBONE_OPTIONS', 'DEFAULT_BACKBONE', 'DEFAULT_LAYERS',
    'DEFAULT_CORESET_RATIO', 'MIN_CORESET_RATIO', 'MAX_CORESET_RATIO',
    'DEFAULT_PCA_COMPONENTS', 'PCA_VARIANCE_THRESHOLD', 'AUTO_PCA_THRESHOLD_DIM',
    'DEFAULT_KNN_K', 'MIN_KNN_K', 'MAX_KNN_K',
    'SCORE_RANGE', 'DEFAULT_THRESHOLD', 'THRESHOLD_PRESETS',
    'CALIBRATION_PERCENTILES',
    'EXPORT_FORMATS', 'DEFAULT_EXPORT_FORMAT',
    'TENSORRT_PRECISIONS', 'DEFAULT_TENSORRT_PRECISION',
    'FAISS_INDEX_TYPES', 'FAISS_AUTO_THRESHOLDS',
    'DEFAULT_USE_FP16_FEATURES', 'DEFAULT_FEATURE_CHUNK_SIZE',
    'DEFAULT_INCREMENTAL_PCA', 'DEFAULT_PCA_BATCH_SIZE',
    'DEFAULT_RANDOM_PROJECTION_DIM', 'DEFAULT_CORESET_MAX_ITER',
    'DEFAULT_FEATURE_BATCH_SIZE', 'DEFAULT_INFERENCE_BATCH_SIZE',
    'OUTPUT_DIRS', 'OUTPUT_FILENAMES',
    'DEVICE_OPTIONS', 'DEFAULT_DEVICE',
    'DEFAULT_GAUSSIAN_SIGMA', 'DEFAULT_GAUSSIAN_KERNEL_SIZE',
    'DEFAULT_UPSAMPLE_MODE',
    'HEATMAP_COLORMAP', 'CONTOUR_COLOR', 'CONTOUR_THICKNESS',
    'SCENE_TEMPLATES', 'AUGMENTATION_CONFIG',
    
    # 配置类
    'TrainingConfig',
    'BackboneConfig',
    'MemoryBankConfig',
    'KNNConfig',
    'PostprocessConfig',
    'NormalizationConfig',
    'ThresholdConfig',
    'ExportConfig',
    'OptimizationConfig',
    'AugmentationConfig',
    
    # 函数
    'get_backbone_info',
]
